# namespace: developer-86
version: 'main'
services:
  config-server:
    containerName: config-server
    image: chitaialm/petclinic
    tag: spring-petclinic-config-server
    commit: "spring-petclinic-config-server-null"
    port: 8888
  customers-service:
    containerName: customers-service
    image: chitaialm/petclinic
    tag: spring-petclinic-customers-service
    commit: "spring-petclinic-customers-service-null"
    port: 8081
  discovery-server:
    containerName: discovery-server
    image: chitaialm/petclinic 
    tag: spring-petclinic-discovery-server
    commit: "spring-petclinic-discovery-server-null"
    port: 8761
  visits-service:
    containerName: visits-service
    image: chitaialm/petclinic
    tag: spring-petclinic-visits-service 
    commit: "spring-petclinic-visits-service-null"
    port: 8082
  vets-service:
    containerName: vets-service
    image: chitaialm/petclinic
    tag: spring-petclinic-vets-service 
    commit: "spring-petclinic-vets-service-null"
    port: 8083
  genai-service:
    containerName: genai-service
    image: chitaialm/petclinic
    tag: spring-petclinic-genai-service
    commit: "spring-petclinic-genai-service-null"
    port: 8084
  api-gateway:
    containerName: api-gateway
    image: chitaialm/petclinic
    tag: spring-petclinic-api-gateway
    commit: "spring-petclinic-api-gateway-null"
    port: 8080
    ingress:
      enabled: true
      host: petclinic-dev.tech
  admin-server:
    containerName: admin-server
    image: chitaialm/petclinic
    tag: spring-petclinic-admin-server
    commit: "spring-petclinic-admin-server-null"
    port: 9090
replicaCount: 1
