spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
  eureka:
    instance:
      prefer-ip-address: true
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
