spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888/}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
